"""Post-hoc diagnostic: score every trained experiment on the frozen test set.

Read-only with respect to model selection. This script runs *after* the
validation-selected production model and its single official frozen-test
evaluation are already locked in
``artifacts/results/frozen_test_evaluation.json``.

It exists for analysis and reporting only:

* it does not participate in model selection, hyperparameter choice,
  temperature fitting, or review-threshold selection;
* it never writes ``frozen_test_evaluation.json``, ``production_ready.json``,
  the final checkpoint, or any file under ``reports/``;
* the official frozen-test result remains the single evaluation recorded in
  ``frozen_test_evaluation.json``.

Because these are per-model test scores, they must not be used to pick a
different production model. Any such change would turn the test set into a
selection tool and invalidate the project's leakage guarantees.

Every path comes from ``configs/paths.json`` via ``traffic_classifier.paths``,
and outputs land in the dedicated directory
``artifacts/results/all_models_test/``:

* ``summary.json`` / ``summary.csv``       one row per experiment
* ``per_image_predictions.csv``            every model x every test image
* ``per_image_predictions.jsonl``          the same rows, one JSON object each
* ``per_model/<experiment>.csv``           one file per experiment
* ``confidence_by_true_class.csv``         confidence/accuracy per true class
* ``README.md``                            column definitions and caveats

Every printed line is mirrored to
``artifacts/logs/all_models_test_diagnostic.log``.
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics
import sys
from pathlib import Path
from typing import Any, TextIO

import numpy as np
import torch
from torch import nn

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from traffic_classifier.config import ProjectConfig  # noqa: E402
from traffic_classifier.data import (  # noqa: E402
    build_transforms,
    load_image_folder,
    make_loader,
)
from traffic_classifier.engine import evaluate  # noqa: E402
from traffic_classifier.metrics import (  # noqa: E402
    classification_metrics,
    confusion_pair_ranking,
)
from traffic_classifier.models import build_model  # noqa: E402
from traffic_classifier.paths import ProjectPaths, load_paths  # noqa: E402
from traffic_classifier.utils import load_checkpoint  # noqa: E402

PER_IMAGE_COLUMNS = [
    "model",
    "display_name",
    "architecture",
    "loss",
    "probability_kind",
    "image_index",
    "image_path",
    "true_class",
    "predicted_class",
    "correct",
    "confidence",
    "margin",
    "true_class_probability",
    "top3",
    "temperature",
    "below_official_review_threshold",
]

BANNER = """\
================================================================================
POST-HOC DIAGNOSTIC - NOT A SELECTION STEP
================================================================================
Every trained experiment below is scored on dataset/test for analysis only.
The production model was already chosen on validation macro-F1, and its single
official test evaluation is already recorded and locked. Nothing printed here
changes that decision. Do not use these numbers to choose a different model.
================================================================================
"""

README_TEMPLATE = """\
# All-model test diagnostic

Generated by `scripts/evaluate_all_models_on_test.py` from `configs/paths.json`.

**These numbers are diagnostic only.** The production model was selected on
validation macro-F1 and evaluated on the frozen test set exactly once; that
official result in `artifacts/results/frozen_test_evaluation.json` is
authoritative and unchanged. These extra per-model test scores exist for
error analysis. Selecting a different model on the basis of this file would
turn the test set into a tuning set and void the leakage guarantees, so it must
not be done.

## Files

| File | Contents |
| --- | --- |
| `summary.json` | Full metrics per experiment, plus the integrity check and protocol echo |
| `summary.csv` | One row per experiment, ranked by test macro-F1 |
| `per_image_predictions.csv` | Every model x every test image ({rows} rows) |
| `per_image_predictions.jsonl` | The same rows as one JSON object per line |
| `per_model/<experiment>.csv` | One file per experiment ({images} rows each) |
| `confidence_by_true_class.csv` | Confidence and accuracy per true class |
| `README.md` | This file |

## Columns in `per_image_predictions.csv`

| Column | Meaning |
| --- | --- |
| `model` | Experiment key from `experiment_results.json` |
| `architecture` | `traffic_cnn` or `resnet18` |
| `loss` | Training loss: `cross_entropy` or `bce` |
| `probability_kind` | `softmax`, or `sigmoid` for the `bce_loss` arm. Sigmoid outputs are not a distribution, so their `confidence` is a per-class score rather than a probability |
| `image_index` | Row index in the test split, in dataset order |
| `image_path` | Path relative to the repository root |
| `true_class` / `predicted_class` | Labels |
| `correct` | Whether the prediction matches the label |
| `confidence` | Score of the **chosen** class, i.e. the top-1 probability |
| `margin` | Top-1 minus top-2 score; a small margin means an ambiguous choice |
| `true_class_probability` | Score assigned to the correct label |
| `top3` | Best three classes as `class:score` separated by `\\|` |
| `temperature` | Temperature applied to the logits. Only the production model uses its validation-fitted temperature; every other model uses 1.0 because no calibration was fitted for it |
| `below_official_review_threshold` | `confidence` under the production review threshold ({threshold:.4f}). This is the *production* threshold shown for reference, **not** a per-model calibrated threshold |

## Integrity check

The production model's macro-F1 is recomputed here and compared with the locked
official value; the run aborts if they disagree by more than 1e-6.
Observed absolute difference: {drift:.3e}.
"""


class _Tee:
    """Mirror stdout into a log file so the whole run is captured."""

    def __init__(self, stream: TextIO, path: Path) -> None:
        self._stream = stream
        self._path = path
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._handle = self._path.open("w", encoding="utf-8")

    def write(self, text: str) -> int:
        self._stream.write(text)
        self._handle.write(text)
        return len(text)

    def flush(self) -> None:
        self._stream.flush()
        self._handle.flush()

    def close(self) -> None:
        if not self._handle.closed:
            self._handle.flush()
            self._handle.close()


def _banner(text: str) -> None:
    print(f"\n{text}\n{'-' * len(text)}")


def _check_transform(expected: dict[str, Any], actual: Any, name: str) -> None:
    """Fail loudly if a rebuilt transform differs from the one used in training."""

    if int(expected["image_size"]) != int(actual.image_size):
        raise RuntimeError(
            f"{name}: evaluation image size {actual.image_size} does not match the "
            f"stored {expected['image_size']}"
        )
    for field in ("normalization_mean", "normalization_std"):
        stored = [float(value) for value in expected[field]]
        rebuilt = [float(value) for value in getattr(actual, field)]
        if len(stored) != len(rebuilt) or any(
            abs(a - b) > 1e-9 for a, b in zip(stored, rebuilt)
        ):
            raise RuntimeError(
                f"{name}: rebuilt {field} {rebuilt} does not match stored {stored}"
            )


def _per_image_rows(
    *,
    name: str,
    entry: dict[str, Any],
    sample_paths: list[str],
    targets: np.ndarray,
    probabilities: np.ndarray,
    classes: list[str],
    temperature: float,
    review_threshold: float,
) -> list[dict[str, Any]]:
    """One row per test image, carrying the confidence of the chosen class."""

    predictions = probabilities.argmax(axis=1)
    rows: list[dict[str, Any]] = []
    for index in range(len(targets)):
        scores = probabilities[index]
        order = np.argsort(-scores)
        top3 = "|".join(
            f"{classes[position]}:{scores[position]:.6f}" for position in order[:3]
        )
        confidence = float(scores[order[0]])
        runner_up = float(scores[order[1]]) if len(order) > 1 else 0.0
        true_index = int(targets[index])
        rows.append(
            {
                "model": name,
                "display_name": entry["display_name"],
                "architecture": entry["architecture"],
                "loss": entry["loss"],
                "probability_kind": entry["_probability_kind"],
                "image_index": index,
                "image_path": sample_paths[index],
                "true_class": classes[true_index],
                "predicted_class": classes[int(order[0])],
                "correct": bool(order[0] == true_index),
                "confidence": confidence,
                "margin": confidence - runner_up,
                "true_class_probability": float(scores[true_index]),
                "top3": top3,
                "temperature": temperature,
                "below_official_review_threshold": bool(
                    confidence < review_threshold
                ),
            }
        )
    return rows


def _confidence_by_class(
    rows: list[dict[str, Any]], classes: list[str]
) -> list[dict[str, Any]]:
    """Aggregate confidence and accuracy per true class, per model."""

    summary: list[dict[str, Any]] = []
    for model in sorted({row["model"] for row in rows}):
        model_rows = [row for row in rows if row["model"] == model]
        for label in classes:
            subset = [row for row in model_rows if row["true_class"] == label]
            if not subset:
                continue
            confidences = [row["confidence"] for row in subset]
            correct = [row["confidence"] for row in subset if row["correct"]]
            wrong = [row["confidence"] for row in subset if not row["correct"]]
            summary.append(
                {
                    "model": model,
                    "true_class": label,
                    "images": len(subset),
                    "accuracy": len(correct) / len(subset),
                    "mean_confidence": statistics.fmean(confidences),
                    "median_confidence": statistics.median(confidences),
                    "min_confidence": min(confidences),
                    "max_confidence": max(confidences),
                    "mean_confidence_when_correct": (
                        statistics.fmean(correct) if correct else ""
                    ),
                    "mean_confidence_when_wrong": (
                        statistics.fmean(wrong) if wrong else ""
                    ),
                }
            )
    return summary


def run(config_path: Path, paths_file: Path | None) -> dict[str, Any]:
    paths = load_paths(paths_file)
    config = ProjectConfig.from_json(paths.get("configs.default"))
    device = config.resolve_device()

    out_dir = paths.ensure_dir("results.all_models_test_dir")
    per_model_dir = out_dir / "per_model"
    per_model_dir.mkdir(parents=True, exist_ok=True)
    log_path = paths.get("logs.all_models_test")

    print(BANNER)
    registry = paths.verify()
    print(f"config        : {paths.relative(config_path)}")
    print(f"paths registry: {registry['source']} ({registry['total_entries']} entries)")
    print(f"output dir    : {paths.relative(out_dir)}")
    print(f"log           : {paths.relative(log_path)}")
    print(f"device        : {device}")

    # --- guard: the official single test evaluation must already exist --------
    frozen_path = paths.get("results.frozen_test_evaluation")
    if not frozen_path.exists():
        raise SystemExit(
            "refusing to run: no official frozen-test evaluation exists yet.\n"
            "Run `python main.py` first so the production model is selected on "
            "validation and evaluated once, then run this diagnostic."
        )
    frozen = json.loads(frozen_path.read_text(encoding="utf-8"))
    protocol = frozen["evaluation_protocol"]
    official_name = frozen["selected_experiment"]
    official_metrics = frozen["test_metrics"]
    official_threshold = float(frozen["review_threshold"]["threshold"])

    _banner("Locked official result (authoritative, not recomputed here)")
    print(f"selected on        : {protocol['selected_using']}")
    print(f"production model   : {official_name}")
    print(f"test evaluations   : {protocol['test_evaluations']}")
    print(f"official test acc  : {official_metrics['accuracy']:.4f}")
    print(f"official test F1   : {official_metrics['macro_f1']:.4f}")
    print(f"temperature        : {frozen['temperature']:.4f}")
    print(f"review threshold   : {official_threshold:.4f}")

    experiments_path = paths.get("results.experiment_results")
    if not experiments_path.exists():
        raise SystemExit(f"missing experiment record: {experiments_path}")
    experiments = json.loads(experiments_path.read_text(encoding="utf-8"))

    # every experiment must agree on the class mapping before we reuse it
    mappings = {
        name: tuple(sorted(entry["metadata"]["class_mapping"].items()))
        for name, entry in experiments.items()
    }
    if len(set(mappings.values())) != 1:
        raise RuntimeError("experiments disagree on the class mapping")
    print(f"\nclass mapping verified identical across {len(experiments)} experiments")

    dataset_cache: dict[str, Any] = {}
    sample_paths: list[str] | None = None
    summary_rows: list[dict[str, Any]] = []
    per_image: list[dict[str, Any]] = []
    reviewed_counts: dict[str, int] = {}

    for name in sorted(experiments):
        entry = experiments[name]
        meta = entry["metadata"]
        stored_transform = meta["evaluation_transform"]
        kind = stored_transform["name"]
        is_bce = entry["loss"] == "bce"
        entry["_probability_kind"] = "sigmoid" if is_bce else "softmax"
        # only the production model has a validation-fitted temperature
        temperature = (
            float(frozen["temperature"]) if name == official_name else 1.0
        )

        transform, spec = build_transforms(
            config, augmentation=False, kind=kind  # type: ignore[arg-type]
        )
        _check_transform(stored_transform, spec, name)

        if kind not in dataset_cache:
            dataset_cache[kind] = load_image_folder(
                f"{ROOT}\\dataset", "test", transform, config.classes
            )
        dataset = dataset_cache[kind]
        loader = make_loader(
            dataset,
            range(len(dataset)),
            training=False,
            batch_size=config.batch_size,
            seed=config.seed,
            num_workers=config.num_workers,
        )

        # SequentialSampler keeps dataset order, so row i of the evaluation
        # output is dataset.samples[i].
        current_paths = [paths.relative(sample[0]) for sample in dataset.samples]
        if sample_paths is None:
            sample_paths = current_paths
        elif current_paths != sample_paths:
            raise RuntimeError(
                "test split ordering differs between transform variants"
            )

        checkpoint_path = paths.get("artifacts.checkpoints_dir") / f"{name}.pt"
        if not checkpoint_path.is_file():
            raise SystemExit(f"missing checkpoint for {name}: {checkpoint_path}")

        model = build_model(
            entry["architecture"],
            len(config.classes),
            dropout=float(meta["dropout"]),
            pooling=meta["pooling"],  # type: ignore[arg-type]
            pretrained=False,
        )
        checkpoint = load_checkpoint(checkpoint_path, map_location=device)
        model.load_state_dict(checkpoint["model_state"])
        model.to(device)

        result = evaluate(
            model,
            loader,
            nn.BCEWithLogitsLoss() if is_bce else nn.CrossEntropyLoss(),
            device,
            loss_name=entry["loss"],
            num_classes=len(config.classes),
            class_names=config.classes,
            probability_kind=entry["_probability_kind"],
            temperature=temperature,
        )
        outputs = result["outputs"]
        targets = outputs["targets"]
        predictions = outputs["predictions"]
        metrics = classification_metrics(targets, predictions, config.classes)
        pairs = confusion_pair_ranking(
            metrics["confusion_matrix_row_normalized"], config.classes
        )

        rows = _per_image_rows(
            name=name,
            entry=entry,
            sample_paths=current_paths,
            targets=targets,
            probabilities=outputs["probabilities"],
            classes=config.classes,
            temperature=temperature,
            review_threshold=official_threshold,
        )
        per_image.extend(rows)
        reviewed_counts[name] = sum(
            1 for row in rows if row["below_official_review_threshold"]
        )
        with (per_model_dir / f"{name}.csv").open(
            "w", encoding="utf-8", newline=""
        ) as handle:
            writer = csv.DictWriter(handle, fieldnames=PER_IMAGE_COLUMNS)
            writer.writeheader()
            writer.writerows(rows)

        summary_rows.append(
            {
                "experiment": name,
                "display_name": entry["display_name"],
                "category": entry["category"],
                "architecture": entry["architecture"],
                "loss": entry["loss"],
                "probability_kind": entry["_probability_kind"],
                "temperature": temperature,
                "best_epoch": entry["best_epoch"],
                "validation_macro_f1": float(entry["validation_metrics"]["macro_f1"]),
                "test_accuracy": float(metrics["accuracy"]),
                "test_macro_precision": float(metrics["macro_precision"]),
                "test_macro_recall": float(metrics["macro_recall"]),
                "test_macro_f1": float(metrics["macro_f1"]),
                "test_errors": int((targets != predictions).sum()),
                "test_images": int(len(targets)),
                "mean_confidence": statistics.fmean(
                    row["confidence"] for row in rows
                ),
                "mean_margin": statistics.fmean(row["margin"] for row in rows),
                "below_review_threshold_images": reviewed_counts[name],
                "top_confusion_pair": (
                    f"{pairs[0]['class_a']}/{pairs[0]['class_b']} "
                    f"({pairs[0]['pair_confusion']:.3f})"
                    if pairs
                    else ""
                ),
                "is_official_production_model": name == official_name,
            }
        )
        print(
            f"evaluated {name:<28} test macro-F1 "
            f"{summary_rows[-1]['test_macro_f1']:.4f} "
            f"acc {summary_rows[-1]['test_accuracy']:.4f} "
            f"errors {summary_rows[-1]['test_errors']}/{summary_rows[-1]['test_images']} "
            f"mean-confidence {summary_rows[-1]['mean_confidence']:.4f}"
        )

    assert sample_paths is not None

    # --- integrity check: our recomputation must match the official record ----
    official_row = next(
        (row for row in summary_rows if row["experiment"] == official_name), None
    )
    if official_row is None:
        raise RuntimeError(
            f"production model {official_name} is absent from the experiment record"
        )
    drift = abs(
        official_row["test_macro_f1"] - float(official_metrics["macro_f1"])
    )
    if drift > 1e-6:
        raise RuntimeError(
            "recomputed test macro-F1 for the production model disagrees with the "
            f"locked record by {drift:.3e}; refusing to publish this diagnostic"
        )
    print(
        f"\nintegrity check passed: recomputed {official_name} test macro-F1 "
        f"{official_row['test_macro_f1']:.6f} matches the locked "
        f"{float(official_metrics['macro_f1']):.6f}"
    )

    expected_rows = len(experiments) * len(sample_paths)
    if len(per_image) != expected_rows:
        raise RuntimeError(
            f"expected {expected_rows} per-image rows, produced {len(per_image)}"
        )
    print(
        f"per-image coverage check passed: {len(per_image)} rows = "
        f"{len(experiments)} models x {len(sample_paths)} test images"
    )

    # cross-check the review flag against the official selective-prediction block
    official_selective = frozen.get("test_selective") or {}
    official_review_rate = official_selective.get("review_rate")
    if official_review_rate is not None:
        ours = reviewed_counts[official_name] / len(sample_paths)
        print(
            f"review-flag cross-check: official test review rate "
            f"{float(official_review_rate):.4f} vs recomputed {ours:.4f} "
            f"(difference {abs(float(official_review_rate) - ours):.4f})"
        )

    summary_rows.sort(key=lambda row: -row["test_macro_f1"])

    _banner("All experiments ranked by test macro-F1 (diagnostic only)")
    header = (
        f"{'test F1':>8}  {'test acc':>8}  {'val F1':>7}  {'conf':>6}  "
        f"{'err':>4}  {'ep':>3}  experiment"
    )
    print(header)
    print("-" * len(header))
    for row in summary_rows:
        marker = " *" if row["is_official_production_model"] else "  "
        print(
            f"{row['test_macro_f1']:>8.4f}  {row['test_accuracy']:>8.4f}  "
            f"{row['validation_macro_f1']:>7.4f}  "
            f"{row['mean_confidence']:>6.4f}  "
            f"{row['test_errors']:>4}  {row['best_epoch']:>3}  "
            f"{row['experiment']}{marker}"
        )
    print("\n* = official production model (selected on validation, test used once)")
    print(
        "conf = mean confidence of the chosen class over all 400 test images"
    )

    imbalance = [row for row in summary_rows if row["category"] == "imbalance"]
    if imbalance:
        _banner("Note on the imbalance arms")
        print(
            "The two imbalance arms were trained on a deliberately reduced subset "
            "(14 images for kamyun/minibus/savari/vanet) to exercise the "
            "BalancedBatchSampler. Their test scores are not comparable to the "
            "full-data arms and cannot be production candidates."
        )

    _banner("Confidence of the chosen class, production model")
    confidences = [
        row["confidence"] for row in per_image if row["model"] == official_name
    ]
    margins = [row["margin"] for row in per_image if row["model"] == official_name]
    print(f"images scored      : {len(confidences)}")
    print(f"mean confidence    : {statistics.fmean(confidences):.4f}")
    print(f"median confidence  : {statistics.median(confidences):.4f}")
    print(f"min confidence     : {min(confidences):.4f}")
    print(f"mean margin        : {statistics.fmean(margins):.4f}")
    print(
        f"below review threshold {official_threshold:.4f} : "
        f"{reviewed_counts[official_name]} images "
        f"({reviewed_counts[official_name] / len(sample_paths):.2%})"
    )
    print(f"top confusion pair : {official_row['top_confusion_pair']}")

    # --- write everything ---------------------------------------------------
    by_class = _confidence_by_class(per_image, config.classes)
    with (out_dir / "per_image_predictions.csv").open(
        "w", encoding="utf-8", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=PER_IMAGE_COLUMNS)
        writer.writeheader()
        writer.writerows(per_image)
    with (out_dir / "per_image_predictions.jsonl").open(
        "w", encoding="utf-8"
    ) as handle:
        for row in per_image:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    with (out_dir / "summary.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(summary_rows[0]))
        writer.writeheader()
        writer.writerows(summary_rows)
    with (out_dir / "confidence_by_true_class.csv").open(
        "w", encoding="utf-8", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=list(by_class[0]))
        writer.writeheader()
        writer.writerows(by_class)

    payload = {
        "purpose": (
            "post-hoc diagnostic; not used for model selection, hyperparameters, "
            "temperature, or review threshold"
        ),
        "generated_by": paths.relative(Path(__file__)),
        "paths_registry": registry,
        "official_evaluation": {
            "file": paths.relative(frozen_path),
            "selected_using": protocol["selected_using"],
            "selected_experiment": official_name,
            "test_evaluations": protocol["test_evaluations"],
            "temperature": float(frozen["temperature"]),
            "review_threshold": official_threshold,
            "test_accuracy": float(official_metrics["accuracy"]),
            "test_macro_f1": float(official_metrics["macro_f1"]),
            "error_count": int(frozen["error_count"]),
        },
        "integrity_check": {
            "recomputed_macro_f1": official_row["test_macro_f1"],
            "locked_macro_f1": float(official_metrics["macro_f1"]),
            "abs_difference": drift,
            "passed": True,
        },
        "coverage": {
            "models": len(experiments),
            "test_images": len(sample_paths),
            "per_image_rows": len(per_image),
            "expected_rows": expected_rows,
        },
        "summary": summary_rows,
        "confidence_by_true_class": by_class,
    }
    (out_dir / "summary.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
    )
    (out_dir / "README.md").write_text(
        README_TEMPLATE.format(
            rows=len(per_image),
            images=len(sample_paths),
            threshold=official_threshold,
            drift=drift,
        ),
        encoding="utf-8",
    )

    _banner("Written")
    for name in sorted(path.name for path in out_dir.iterdir()):
        print(f"  {paths.relative(out_dir / name)}")
    print(f"  {paths.relative(per_model_dir)}/ ({len(experiments)} files)")
    print(f"  {paths.relative(log_path)}")
    print(
        "\nReminder: the official result is unchanged and remains the single "
        "frozen-test evaluation recorded in frozen_test_evaluation.json."
    )
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Post-hoc diagnostic: score every trained experiment on dataset/test, "
            "with a per-image confidence row for every model and every image. "
            "Runs only after the official single frozen-test evaluation exists."
        )
    )
    parser.add_argument("--config", default="configs/default.json")
    parser.add_argument("--paths", default=None)
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = ROOT / config_path

    # open the log before anything else so even a guard failure is captured
    log_path = load_paths(args.paths).get("logs.all_models_test")
    tee = _Tee(sys.__stdout__, log_path)
    sys.stdout = tee
    try:
        run(config_path, Path(args.paths) if args.paths else None)
    finally:
        sys.stdout = tee._stream
        tee.close()


if __name__ == "__main__":
    main()